# Conda environment specification for StructureBased_GJI Project
# This file can be used to recreate the gempyenvf environment
# Usage: conda env create -f environment.yml

name: gempyenvf
channels:
  - conda-forge
  - defaults
  - gimli

dependencies:
  - python=3.11.8
  
  # Core scientific computing
  - numpy=1.24.4
  - scipy=1.10.1
  - matplotlib=3.4.1
  - pandas=2.0.1
  
  # Geophysical modeling
  - pygimli  # Available from gimli channel
  - gempy=2.2.0
  
  # Mesh and visualization
  - meshio=4.3.8
  - pyvista=0.39.1
  - vtk=9.0.1
  
  # Data science and analysis
  - scikit-learn=1.3.2
  - scikit-image=0.19.3
  - seaborn=0.12.1
  - h5py=3.7.0
  - netcdf4=1.5.6
  - xarray=2023.1.0
  
  # Jupyter ecosystem
  - jupyter
  - jupyterlab=4.1.3
  - ipython=8.12.2
  - ipykernel=6.29.3
  - matplotlib-inline=0.1.6
  
  # Development tools
  - black=24.2.0
  - flake8=7.0.0
  - pytest=7.3.2
  - jupytext=1.16.1
  
  # Utility libraries
  - tqdm=4.66.2
  - requests=2.31.0
  - pyyaml=6.0.1
  
  # Optional scientific libraries
  - pooch=1.8.1
  - verde=1.8.0
  
  # System dependencies
  - ca-certificates
  - certifi
  
  # Pip dependencies (packages not available through conda)
  - pip
  - pip:
    - pygimli  # Fallback if conda channel doesn't work